version: "3.8"

services:
  api:
    build: .
    depends_on:
      - db
    expose:
      - 8000
    env_file:
      - ./.env
  
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
  
  nginx:
    build: nginx/
    depends_on:
      - api
    ports:
      - 80:80

volumes:
  postgres-data: