version: "3.8"

services:
  api:
    build: .
    depends_on:
      - db
    expose:
      - 8000
    env_file:
      - ./.env
    networks:
      - net
  
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - net
  
  nginx:
    image: nginx:latest
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/sites-available
    networks:
      - net

volumes:
  postgres-data:

networks:
  net:
